// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "KovanicaWallet",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "KovanicaWallet",
            targets: ["KovanicaWallet"]),
    ],
    dependencies: [
        // Kovanica FFI Swift bindings (generated by UniFFI from Rust)
        // .package(path: "../../sdk/crates/kovanica-ffi-swift"),
        
        // For keychain storage
        .package(url: "https://github.com/evgenyneu/keychain-swift.git", from: "24.0.0"),
        
        // For BIP-39 mnemonic (if not using FFI)
        .package(url: "https://github.com/bitmark-inc/bip39swift.git", from: "1.0.0"),
        
        // BouncyCastle for crypto (via Swift Crypto)
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
    ],
    targets: [
        .target(
            name: "KovanicaWallet",
            dependencies: [
                .product(name: "KeychainSwift", package: "keychain-swift"),
                .product(name: "BIP39Swift", package: "bip39swift"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            path: "KovanicaWallet",
            exclude: ["Info.plist"],
            resources: [
                .process("Resources")
            ]
        ),
        .testTarget(
            name: "KovanicaWalletTests",
            dependencies: ["KovanicaWallet"],
            path: "KovanicaWalletTests"
        ),
    ]
)