#!/usr/bin/env bash
# Compile and run the iOS wallet's key-derivation known-answer tests on Linux.
#
# Why this exists
# ---------------
# `mobile/ios/KovanicaWallet/KovanicaKeys.swift` is the only client-side code
# that turns a recovery phrase into a Kovanica address, and the derivation rule
# is frozen. A wallet that derives the wrong address shows a permanent zero
# balance and sends to a keypair holding no outputs, so these vectors must be
# asserted everywhere the derivation is implemented — not only on the macOS
# runner, which builds far less often than the Linux one.
#
# `KovanicaKeys.swift` is plain Foundation over the light-node FFI, so it
# compiles and runs on Linux against the same generated bindings iOS uses. Only
# the SwiftUI app target needs macOS.
#
# The harness is assembled into a temp directory from the *real* sources — no
# copies are committed — so it cannot drift from what ships.
#
# Usage:  mobile/ios/run-swift-kat.sh
# Needs:  a Swift toolchain (`apt install swiftlang` on Ubuntu) and cargo.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
FFI_CRATE="$REPO_ROOT/protocol/crates/kovanica-ffi"
SWIFT_DIR="$REPO_ROOT/mobile/ios"

command -v swift >/dev/null || { echo "no swift toolchain on PATH" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "==> building the FFI shared object"
cargo build --release -p kovanica-ffi --manifest-path "$REPO_ROOT/protocol/Cargo.toml"
LIBDIR="$REPO_ROOT/protocol/target/release"
[ -f "$LIBDIR/libkovanica_ffi.so" ] || { echo "missing libkovanica_ffi.so" >&2; exit 1; }

echo "==> staging the harness in $WORK"
mkdir -p "$WORK/Sources/KovanicaKeysLinux" \
         "$WORK/Sources/CCovanicaFFI/include" \
         "$WORK/Tests/KovanicaKeysLinuxTests"

# The real, committed sources under test.
cp "$FFI_CRATE/bindings/swift/kovanica.swift"      "$WORK/Sources/KovanicaKeysLinux/"
cp "$SWIFT_DIR/KovanicaWallet/KovanicaKeys.swift"   "$WORK/Sources/KovanicaKeysLinux/"
cp "$SWIFT_DIR/KovanicaWalletTests/KovanicaKeysTests.swift" \
   "$WORK/Tests/KovanicaKeysLinuxTests/"
sed -i 's/^@testable import KovanicaWallet$/@testable import KovanicaKeysLinux/' \
   "$WORK/Tests/KovanicaKeysLinuxTests/KovanicaKeysTests.swift"

# The generated header + a module map. UniFFI's own module map is macOS-shaped
# (`use "Darwin"`); on Linux the symbols come from the shared object, so link it.
cp "$FFI_CRATE/bindings/swift/kovanicaFFI.h" "$WORK/Sources/CCovanicaFFI/include/"
cat > "$WORK/Sources/CCovanicaFFI/include/module.modulemap" <<'MODULEMAP'
module kovanicaFFI {
    header "kovanicaFFI.h"
    export *
    link "kovanica_ffi"
}
MODULEMAP
# A C target needs at least one translation unit; the library is linked, not built.
cat > "$WORK/Sources/CCovanicaFFI/anchor.c" <<'ANCHOR'
/* The FFI object is linked, not compiled. This exists so SwiftPM builds the
   Clang module for the generated header. */
ANCHOR

cat > "$WORK/Package.swift" <<PACKAGE
// swift-tools-version: 5.9
// Generated by mobile/ios/run-swift-kat.sh — edit the script, not this file.
import PackageDescription

// Pass the search path and an rpath to the linker directly. Relying on
// LIBRARY_PATH alone is not enough: the CI runner links with ld.gold via
// SwiftPM, which does not pass that variable through, and the build then fails
// with "cannot find -lkovanica_ffi". The rpath also lets the test bundle find
// the shared object at runtime without depending on LD_LIBRARY_PATH.
let ffiLink: [LinkerSetting] = [
    .unsafeFlags(["-L$LIBDIR", "-Xlinker", "-rpath", "-Xlinker", "$LIBDIR"])
]

let package = Package(
    name: "KovanicaKeysLinux",
    products: [.library(name: "KovanicaKeysLinux", targets: ["KovanicaKeysLinux"])],
    targets: [
        .target(
            name: "CCovanicaFFI",
            path: "Sources/CCovanicaFFI",
            linkerSettings: ffiLink
        ),
        .target(
            name: "KovanicaKeysLinux",
            dependencies: ["CCovanicaFFI"],
            path: "Sources/KovanicaKeysLinux",
            linkerSettings: ffiLink
        ),
        .testTarget(
            name: "KovanicaKeysLinuxTests",
            dependencies: ["KovanicaKeysLinux"],
            path: "Tests/KovanicaKeysLinuxTests",
            linkerSettings: ffiLink
        ),
    ],
    swiftLanguageVersions: [.v5]
)
PACKAGE

echo "==> running the derivation known-answer tests"
cd "$WORK"
LIBRARY_PATH="$LIBDIR" LD_LIBRARY_PATH="$LIBDIR" swift test
